# Site settings
title:        Andrei Bârsan's Website
email:        andrei.ioan.barsan@gmail.com
description: >
  PhD Student at the University of Toronto working in computer vision and
  machine learning.
baseurl:      ""
# domain_name:  "http://siegedog.com"
future:       true

# Build settings
markdown:     kramdown
highlighter:  pygments
plugins: [jekyll-paginate]

# Custom 404 page.
permalink: /404.html

# TODO(andrei): Possibly increase this in the future.
paginate:     5
#google_analytics: 'UA-XXXXXXXX-X'
disqus_shortname: 'andreibarsan'

# Details for the RSS feed generator
url:            "http://siegedog.com"
author:         "Andrei Bârsan"

twitter_username:  "andreib"
github_username: AndreiBarsan

# Otherwise the permalink gets "spammed" with all the tags...
permalink:       /:year/:month/:day/:title/

excerpt_separator: "<!--more-->"

plugins: [jekyll-paginate]

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

