# Site settings
title: "Andrei Bârsan's Blog"
email: andrei.ioan.barsan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Andrei Bârsan's blog—ramblings ranging from low-level reverse engineering
  to game development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: andreibarsan.github.io # the base hostname & protocol for your site
twitter_username: andreib
github_username: andreibarsan

# Build settings
markdown: kramdown
highlighter: pygments

# Outputting
permalink:     date
paginate_path: /page:num
