# Site settings
title: "Andrei Bârsan's Blog"
email: andrei.ioan.barsan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Andrei Bârsan's blog—ramblings ranging from low-level reverse engineering
  to game development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: andreibarsan.github.io # the base hostname & protocol for your site
twitter_username: andreib
github_username: andreibarsan

# Build settings
markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://siegedog.com'
#google_analytics: 'UA-XXXXXXXX-X'
#disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://siegedog.com'
author:         'CHANGE THIS YO'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

aboutPage: true
