# Site settings
title:        Andrei Bârsan's Website
email:        andrei.ioan.barsan@gmail.com
description: >
  PhD Student at the University of Toronto working in computer vision and
  machine learning.
baseurl:      ""
# domain_name:  "http://siegedog.com"
future:       true
timezone:     America/Toronto

# Build settings
markdown:     kramdown
highlighter:  rouge
# plugins: [jekyll-paginate]

# Custom 404 page.
permalink: /404.html

# paginate:     5
disqus_shortname: 'andreibarsan'

# Details for the RSS feed generator
url:            "http://siegedog.com"
author:         "Andrei Bârsan"

twitter_username:  "andreib"
github_username: AndreiBarsan

# Otherwise the permalink gets "spammed" with all the tags...
permalink:       /:year/:month/:day/:title/

excerpt_separator: "<!--more-->"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

people:
  ajyang:
    name: Joyce Yang
    site: http://www.cs.toronto.edu/~ajyang/

  barsan:
    name: Ioan Andrei Bârsan
    not_used_site: https://andreibarsan.github.io    # No point in linking to my own website ;)

  bai:
    name: Min Bai
    site: http://www.cs.toronto.edu/~mbai/

  cuic:
    name: Can Cui
    site: https://github.com/cancui

  doubov:
    name: Sasha Doubov
    site: https://www.linkedin.com/in/sashadoubov/

  fan:
    name: Jack Fan
    site: https://www.linkedin.com/in/jack-fan-87556734

  frossard:
    name: Davi Frossard
    site: https://www.cs.toronto.edu/~frossard/about/

  geiger:
    name: Andreas Geiger
    site: http://www.cvlibs.net

  homayounfar:
    name: Namdar Homayounfar
    site: http://www.cs.toronto.edu/~namdar/

  liu:
    name: Peidong Liu
    site: http://people.inf.ethz.ch/liup/

  ma:
    name: Wei-Chiu Ma
    site: https://people.csail.mit.edu/weichium/

  martinez:
    name: Julieta Martinez
    site: https://una-dinosauria.github.io/

  mattyus:
    name: Gellért Máttyus
    site: http://www.gellertmattyus.info

  lakshmikanth:
    name: Shrinidhi Kowshika Lakshmikanth
    site: https://scholar.google.com/citations?user=UjpM6IAAAAAJ&hl=en

  pokrovsky:
    name: Andrei Pokrovsky
    site: https://scholar.google.com/citations?user=0jJgmHkAAAAJ&hl=en

  pollefeys:
    name: Marc Pollefeys
    site: https://people.inf.ethz.ch/pomarc/

  suo:
    name: Simon Suo
    site: http://www.cs.toronto.edu/~suo/

  tartavull:
    name: Ignacio Tartavull
    site: http://tartavull.com/

  urtasun:
    name: Raquel Urtasun
    site: https://www.cs.toronto.edu/~urtasun/

  wang:
    name: Shenlong Wang
    site: http://www.cs.toronto.edu/~slwang/

  wei:
    name: Xinkai Wei
    site: https://kyewei.com


